name: HowToWorkWith-test
on: [push]
jobs:
  HowToWorkWith-test:
  runs-on: ubuntu-20.04
  steps:
    - run:  
      echo *** LOAD ***
      sudo mkdir -p /home/HowtoWorkwithGit/
      sudo git clone https://github.com/sung-jun98/HowtoWorkwithGit.git /home/HowToWorkWith/
      cd /home/HowToWorkWith/
      echo *** LOAD ***
      
      echo *** INSTALL ***
      sudo apt-get update
      sudo apt install python3-pip
      
      sudo apt install python3-pytest
      
      echo *** INTSTALL *** 
      echo *** TEST ***
      pytest-3 testFile.py --disable-warnings
      echo *** TEST ***
      
 
